/* Schilderwald – Lerninhalte.
   Grundlage: StVO in der Fassung der Änderung vom 30.01.2026 (gesetze-im-internet.de),
   Zeichennamen nach dem Verkehrszeichenkatalog,
   dazu StVG, FeV und StVZO, wo angegeben. Texte sind eigene Zusammenfassungen. */
(function (global) {
  'use strict';

  const GRUPPEN = [
    { id: 'gefahr', name: 'Gefahrzeichen', info: 'Mahnen zu erhöhter Aufmerksamkeit, vor allem zum Langsamerfahren. Außerorts stehen sie meist 150 bis 250 m vor der Gefahrstelle, innerorts kurz davor (§ 40).' },
    { id: 'vorschrift', name: 'Vorschriftzeichen', info: 'Ordnen Ge- oder Verbote an. Sie gelten ab dem Schild – steht es weiter entfernt, sagt ein Zusatzzeichen, wie weit (§ 41).' },
    { id: 'richt', name: 'Richtzeichen', info: 'Geben Hinweise, können aber auch Ge- oder Verbote enthalten (§ 42).' },
    { id: 'wegweiser', name: 'Wegweiser und Umleitungen', info: 'Gelb außerhalb von Autobahnen, blau für Autobahnen und den Weg dorthin, weiß für Ziele innerhalb von Orten (StVO Anlage 3, Abschnitte 10 bis 12).' },
    { id: 'markierung', name: 'Markierungen', info: 'Auch Markierungen sind Verkehrszeichen. Sie sind weiß; gelbe gelten vorübergehend und heben weiße auf (§ 39 Abs. 5).' },
    { id: 'einrichtung', name: 'Verkehrseinrichtungen', info: 'Absperrungen, Baken und Leitpfosten. Abgesperrte Flächen dürfen nicht befahren werden (§ 43, Anlage 4).' },
    { id: 'licht', name: 'Ampeln und Polizei', info: 'Reihenfolge: Polizei vor Ampel vor Schildern vor Grundregeln (§ 36, § 37).' },
    { id: 'zusatz', name: 'Zusatzzeichen', info: 'Stehen in der Regel unter dem Zeichen, auf das sie sich beziehen, und schränken es ein oder erweitern es (§ 39 Abs. 3).' }
  ];

  /* form: bestimmt, welche Zeichen als falsche Antworten nebeneinander stehen */
  const S = (id, name, gruppe, form, text, quelle, nr) => ({ id, nr: nr === undefined ? id : nr, name, gruppe, form, text, quelle });
  const A1 = 'StVO Anlage 1', A2 = 'StVO Anlage 2', A3 = 'StVO Anlage 3', A4 = 'StVO Anlage 4', VZ = 'Verkehrszeichenkatalog';

  const SCHILDER = [
    // Anlage 1 – Gefahrzeichen
    S('101', 'Gefahrstelle', 'gefahr', 'dreieck', 'Allgemeine Gefahrstelle. Ein Zusatzzeichen kann die Gefahr näher bezeichnen.', A1),
    S('101-11', 'Fußgängerüberweg (Gefahrzeichen)', 'gefahr', 'dreieck', 'Warnt vor einem Zebrastreifen, etwa wenn er schlecht zu sehen ist. Fußgängern das Überqueren ermöglichen, nicht überholen.', '§ 39 Abs. 8, § 26'),
    S('101-12', 'Viehtrieb', 'gefahr', 'dreieck', 'Mit Tieren auf der Fahrbahn rechnen, die getrieben werden.', '§ 39 Abs. 8'),
    S('101-13', 'Reiter', 'gefahr', 'dreieck', 'Mit Reitern auf oder an der Fahrbahn rechnen.', '§ 39 Abs. 8'),
    S('101-15', 'Steinschlag', 'gefahr', 'dreieck', 'Steine können herabfallen oder auf der Fahrbahn liegen.', '§ 39 Abs. 8'),
    S('101-51', 'Schnee- oder Eisglätte', 'gefahr', 'dreieck', 'Mit Glätte durch Schnee oder Eis rechnen.', '§ 39 Abs. 8'),
    S('101-52', 'Splitt, Schotter', 'gefahr', 'dreieck', 'Loser Splitt oder Schotter: Rutschgefahr, und hochgeschleuderte Steine können andere treffen.', '§ 39 Abs. 8'),
    S('101-53', 'Ufer', 'gefahr', 'dreieck', 'Die Straße führt an ein ungesichertes Ufer, etwa an einer Fähre oder einem Kai.', '§ 39 Abs. 8'),
    S('101-54', 'Unzureichendes Lichtraumprofil', 'gefahr', 'dreieck', 'Etwas ragt in den Raum über oder neben der Fahrbahn, zum Beispiel Äste – Vorsicht mit hohen Fahrzeugen und Ladung.', '§ 39 Abs. 8'),
    S('102', 'Kreuzung oder Einmündung', 'gefahr', 'dreieck', 'Kreuzung oder Einmündung mit Vorfahrt von rechts – hier gilt rechts vor links.', A1),
    S('103-10', 'Kurve (links)', 'gefahr', 'dreieck', 'Linkskurve. Geschwindigkeit rechtzeitig vorher anpassen.', A1),
    S('103-20', 'Kurve (rechts)', 'gefahr', 'dreieck', 'Rechtskurve. Geschwindigkeit rechtzeitig vorher anpassen.', A1),
    S('105-10', 'Doppelkurve (zunächst links)', 'gefahr', 'dreieck', 'Zwei aufeinanderfolgende Kurven, die erste nach links.', A1),
    S('105-20', 'Doppelkurve (zunächst rechts)', 'gefahr', 'dreieck', 'Zwei aufeinanderfolgende Kurven, die erste nach rechts.', A1),
    S('108', 'Gefälle', 'gefahr', 'dreieck', 'Gefälle. 10 % heißt: 10 m Höhenunterschied auf 100 m Strecke. Rechtzeitig herunterschalten.', A1),
    S('110', 'Steigung', 'gefahr', 'dreieck', 'Steigung, hier 10 %.', A1),
    S('112', 'Unebene Fahrbahn', 'gefahr', 'dreieck', 'Die Fahrbahn ist uneben, zum Beispiel durch Schlaglöcher oder Bodenwellen.', A1),
    S('114', 'Schleuder- oder Rutschgefahr', 'gefahr', 'dreieck', 'Schleuder- oder Rutschgefahr bei Nässe oder Schmutz.', A1),
    S('117', 'Seitenwind', 'gefahr', 'dreieck', 'Mit starkem Seitenwind rechnen, hier von rechts – etwa auf Brücken oder an Waldschneisen.', A1),
    S('120', 'Verengte Fahrbahn', 'gefahr', 'dreieck', 'Die Fahrbahn wird von beiden Seiten schmaler.', A1),
    S('121-10', 'Einseitig verengte Fahrbahn (rechts)', 'gefahr', 'dreieck', 'Die Fahrbahn wird rechts schmaler.', A1),
    S('121-20', 'Einseitig verengte Fahrbahn (links)', 'gefahr', 'dreieck', 'Die Fahrbahn wird links schmaler.', A1),
    S('123', 'Arbeitsstelle', 'gefahr', 'dreieck', 'Baustelle auf oder an der Straße.', A1),
    S('124', 'Stau', 'gefahr', 'dreieck', 'Mit Stau und einem Stauende rechnen.', A1),
    S('125', 'Gegenverkehr', 'gefahr', 'dreieck', 'Ab hier gibt es Gegenverkehr, etwa nach einem Abschnitt mit nur einer Fahrtrichtung.', A1),
    S('131', 'Lichtzeichenanlage', 'gefahr', 'dreieck', 'Eine Ampel folgt.', A1),
    S('133', 'Fußgänger', 'gefahr', 'dreieck', 'Mit Fußgängern auf der Fahrbahn rechnen.', A1),
    S('136', 'Kinder', 'gefahr', 'dreieck', 'Mit Kindern rechnen. Gegenüber Kindern gilt: langsamer fahren und bremsbereit sein, eine Gefährdung muss ausgeschlossen sein (§ 3 Abs. 2a).', A1),
    S('138', 'Radverkehr', 'gefahr', 'dreieck', 'Radfahrer kreuzen oder fahren auf der Fahrbahn.', A1),
    S('142', 'Wildwechsel', 'gefahr', 'dreieck', 'Mit Wild auf der Fahrbahn rechnen.', A1),
    S('151', 'Bahnübergang', 'gefahr', 'dreieck', 'Bahnübergang, die Bahn hat Vorrang. Ab diesem Zeichen bis einschließlich Bahnübergang keine Kraftfahrzeuge überholen (§ 19 Abs. 1).', A1),
    S('156', 'Bahnübergang mit dreistreifiger Bake', 'gefahr', 'bake', 'Etwa 240 m vor dem Bahnübergang. Ab hier gilt das Überholverbot für Kraftfahrzeuge (§ 19 Abs. 1).', A1),
    S('159', 'Zweistreifige Bake', 'gefahr', 'bake', 'Etwa 160 m vor dem Bahnübergang.', A1),
    S('162', 'Einstreifige Bake', 'gefahr', 'bake', 'Etwa 80 m vor dem Bahnübergang.', A1),

    // Anlage 2 – Vorschriftzeichen
    S('201', 'Andreaskreuz', 'vorschrift', 'sonder', 'Die Bahn hat Vorrang. Bis 10 m davor nicht halten, wenn das Zeichen dadurch verdeckt wird. Nicht parken: innerorts bis je 5 m, außerorts bis je 50 m davor und dahinter.', A2),
    S('201-51', 'Andreaskreuz mit Blitzpfeil', 'vorschrift', 'sonder', 'Wie das Andreaskreuz – der Blitzpfeil zeigt zusätzlich eine Oberleitung unter Spannung an.', A2),
    S('205', 'Vorfahrt gewähren.', 'vorschrift', 'sonder', 'Du musst Vorfahrt gewähren. Bis 10 m davor nicht halten, wenn das Zeichen dadurch verdeckt wird.', A2),
    S('206', 'Halt. Vorfahrt gewähren.', 'vorschrift', 'sonder', 'Du musst anhalten und Vorfahrt gewähren – an der Haltlinie, ohne Haltlinie dort, wo du die andere Straße überblickst.', A2),
    S('208', 'Vorrang des Gegenverkehrs', 'vorschrift', 'rund-rot', 'An der Engstelle musst du den Gegenverkehr zuerst durchfahren lassen.', A2),
    S('209', 'Vorgeschriebene Fahrtrichtung rechts', 'vorschrift', 'rund-blau', 'Du musst der vorgeschriebenen Fahrtrichtung folgen, hier nach rechts.', A2),
    S('209-10', 'Vorgeschriebene Fahrtrichtung links', 'vorschrift', 'rund-blau', 'Du musst der vorgeschriebenen Fahrtrichtung folgen, hier nach links.', A2),
    S('209-30', 'Vorgeschriebene Fahrtrichtung geradeaus', 'vorschrift', 'rund-blau', 'Nur geradeaus weiterfahren.', A2),
    S('211', 'Vorgeschriebene Fahrtrichtung – hier rechts', 'vorschrift', 'rund-blau', 'Du musst hier nach rechts fahren.', A2),
    S('214', 'Vorgeschriebene Fahrtrichtung – geradeaus oder rechts', 'vorschrift', 'rund-blau', 'Nur geradeaus oder nach rechts erlaubt.', A2),
    S('214-30', 'Vorgeschriebene Fahrtrichtung – rechts oder links', 'vorschrift', 'rund-blau', 'Nur nach rechts oder nach links erlaubt, nicht geradeaus.', A2),
    S('215', 'Kreisverkehr', 'vorschrift', 'rund-blau', 'Rechts herum fahren, die Mittelinsel nicht überfahren (Ausnahme: große Fahrzeuge, die anders nicht durchkommen) und auf der Kreisfahrbahn nicht halten. Steht darüber Zeichen 205, hat der Verkehr im Kreis Vorfahrt und beim Einfahren wird nicht geblinkt (§ 8 Abs. 1a).', A2),
    S('220', 'Einbahnstraße', 'vorschrift', 'sonder', 'Die Fahrbahn darf nur in Pfeilrichtung befahren werden. In Einbahnstraßen darf auch links gehalten und geparkt werden (§ 12 Abs. 4).', A2),
    S('222', 'Rechts vorbei', 'vorschrift', 'rund-blau', 'Du musst rechts vorbeifahren, zum Beispiel an einer Verkehrsinsel.', A2),
    S('222-10', 'Links vorbei', 'vorschrift', 'rund-blau', 'Du musst links vorbeifahren.', A2),
    S('223.1', 'Seitenstreifen befahren', 'vorschrift', 'eckig-blau', 'Der Seitenstreifen ist freigegeben und wird wie ein rechter Fahrstreifen befahren.', A2),
    S('223.2', 'Seitenstreifen nicht mehr befahren', 'vorschrift', 'eckig-blau', 'Die Freigabe des Seitenstreifens ist aufgehoben.', A2),
    S('223.3', 'Seitenstreifen räumen', 'vorschrift', 'eckig-blau', 'Wer auf dem Seitenstreifen fährt, muss ihn verlassen.', A2),
    S('224', 'Haltestelle', 'vorschrift', 'sonder', 'Haltestelle für Linienbusse, Straßenbahnen und Schulbusse. Bis je 15 m davor und dahinter nicht parken.', A2),
    S('229', 'Taxenstand', 'vorschrift', 'eckig-blau', 'Halten verboten – ausgenommen Taxen, die für Fahrgäste bereitstehen.', A2),
    S('230', 'Ladebereich', 'vorschrift', 'eckig-blau', 'Halten und Parken nur zum Be- und Entladen, und das ohne Verzögerung.', A2),
    S('237', 'Radweg', 'vorschrift', 'rund-blau', 'Radfahrer müssen den Radweg benutzen, anderer Verkehr darf es nicht.', A2),
    S('238', 'Reitweg', 'vorschrift', 'rund-blau', 'Reiter müssen den Reitweg benutzen (auch wer Pferde führt), anderer Verkehr darf es nicht.', A2),
    S('239', 'Gehweg', 'vorschrift', 'rund-blau', 'Nur für Fußgänger. Ist anderer Verkehr per Zusatzzeichen erlaubt, dann nur mit Schrittgeschwindigkeit.', A2),
    S('240', 'Gemeinsamer Geh- und Radweg', 'vorschrift', 'rund-blau', 'Radfahrer müssen ihn benutzen und auf Fußgänger Rücksicht nehmen.', A2),
    S('241', 'Getrennter Rad- und Gehweg', 'vorschrift', 'rund-blau', 'Radfahrer müssen ihren Teil des Weges benutzen (hier links), Fußgänger den anderen.', A2),
    S('242.1', 'Beginn einer Fußgängerzone', 'vorschrift', 'zone', 'Nur für Fußgänger. Fahrzeuge, die per Zusatzzeichen erlaubt sind, fahren Schrittgeschwindigkeit.', A2),
    S('242.2', 'Ende einer Fußgängerzone', 'vorschrift', 'zone', 'Die Fußgängerzone endet. Wer aus ihr herausfährt, muss eine Gefährdung anderer ausschließen (§ 10).', A2),
    S('244.1', 'Beginn einer Fahrradstraße', 'vorschrift', 'zone', 'Andere Fahrzeuge nur, wenn ein Zusatzzeichen es erlaubt. Höchstens 30 km/h, Radfahrer dürfen nebeneinander fahren.', A2),
    S('244.2', 'Ende einer Fahrradstraße', 'vorschrift', 'zone', 'Die Fahrradstraße endet.', A2),
    S('244.3', 'Beginn einer Fahrradzone', 'vorschrift', 'zone', 'Wie eine Fahrradstraße für ein ganzes Gebiet: anderer Fahrzeugverkehr nur mit Zusatzzeichen, höchstens 30 km/h, Rad- und E-Scooter-Fahrer dürfen nebeneinander fahren.', A2),
    S('244.4', 'Ende einer Fahrradzone', 'vorschrift', 'zone', 'Die Fahrradzone endet.', A2),
    S('245', 'Bussonderfahrstreifen', 'vorschrift', 'rund-blau', 'Nur für Linienbusse und gekennzeichnete Schulbusse. Taxen, Fahrräder oder E-Autos nur mit Zusatzzeichen.', A2),
    S('250', 'Verbot für Fahrzeuge aller Art', 'vorschrift', 'rund-rot', 'Keine Fahrzeuge. Krafträder und Fahrräder dürfen geschoben werden.', A2),
    S('251', 'Verbot für Kraftwagen', 'vorschrift', 'rund-rot', 'Verbot für Kraftwagen und sonstige mehrspurige Kraftfahrzeuge.', A2),
    S('253', 'Verbot für Kraftfahrzeuge über 3,5 t', 'vorschrift', 'rund-rot', 'Gilt für Kfz über 3,5 t zulässiger Gesamtmasse (mit Anhänger) und für Zugmaschinen – Pkw und Busse ausgenommen.', A2),
    S('254', 'Verbot für Radverkehr', 'vorschrift', 'rund-rot', 'Verbot für Radfahrer und E-Scooter.', A2),
    S('255', 'Verbot für Krafträder', 'vorschrift', 'rund-rot', 'Verbot für Krafträder, auch mit Beiwagen, Kleinkrafträder und Mofas.', A2),
    S('257-50', 'Verbot für Mofas', 'vorschrift', 'rund-rot', 'Mofas dürfen hier nicht fahren.', 'StVO Anlage 2 Nr. 26'),
    S('257-54', 'Verbot für Kraftomnibusse', 'vorschrift', 'rund-rot', 'Busse dürfen hier nicht fahren.', 'StVO Anlage 2 Nr. 26'),
    S('257-55', 'Verbot für Personenkraftwagen', 'vorschrift', 'rund-rot', 'Pkw dürfen hier nicht fahren.', 'StVO Anlage 2 Nr. 26'),
    S('257-56', 'Verbot für Pkw mit Anhänger', 'vorschrift', 'rund-rot', 'Pkw mit Anhänger dürfen hier nicht fahren.', 'StVO Anlage 2 Nr. 26'),
    S('257-59', 'Verbot für E-Scooter', 'vorschrift', 'rund-rot', 'Elektrokleinstfahrzeuge dürfen hier nicht fahren.', 'StVO Anlage 2 Nr. 26'),
    S('259', 'Verbot für Fußgänger', 'vorschrift', 'rund-rot', 'Fußgänger dürfen hier nicht gehen.', A2),
    S('260', 'Verbot für Kraftfahrzeuge', 'vorschrift', 'rund-rot', 'Verbot für Krafträder (auch Mofas) und für Kraftwagen.', A2),
    S('261', 'Verbot für Kfz mit gefährlichen Gütern', 'vorschrift', 'rund-rot', 'Verbot für kennzeichnungspflichtige Kraftfahrzeuge mit gefährlichen Gütern.', A2),
    S('262', 'Tatsächliche Masse', 'vorschrift', 'rund-rot', 'Verbot für Fahrzeuge, die mit Ladung tatsächlich schwerer sind als angegeben (hier 5,5 t). Bei Gespannen gilt es für jedes einzelne Fahrzeug.', A2),
    S('263', 'Tatsächliche Achslast', 'vorschrift', 'rund-rot', 'Verbot, wenn die tatsächliche Achslast die Angabe (hier 8 t) übersteigt.', A2),
    S('264', 'Tatsächliche Breite', 'vorschrift', 'rund-rot', 'Verbot für Fahrzeuge, die breiter sind als angegeben – gemessen mit Außenspiegeln.', A2),
    S('265', 'Tatsächliche Höhe', 'vorschrift', 'rund-rot', 'Verbot für Fahrzeuge, die mit Ladung höher sind als angegeben.', A2),
    S('266', 'Tatsächliche Länge', 'vorschrift', 'rund-rot', 'Verbot für Fahrzeuge, die länger sind als angegeben; bei Gespannen zählt die Gesamtlänge.', A2),
    S('267', 'Verbot der Einfahrt', 'vorschrift', 'rund-rot', 'In diese Fahrbahn darf nicht eingefahren werden.', A2),
    S('268', 'Schneeketten vorgeschrieben', 'vorschrift', 'rund-blau', 'Nur mit Schneeketten befahren – mit Ketten gilt höchstens 50 km/h (§ 3 Abs. 4).', A2),
    S('269', 'Verbot für Fahrzeuge mit wassergefährdender Ladung', 'vorschrift', 'rund-rot', 'Mit mehr als 20 l wassergefährdender Ladung darf die Straße nicht benutzt werden.', A2),
    S('270.1', 'Beginn einer Umweltzone', 'vorschrift', 'zone', 'Kraftfahrzeuge dürfen nur mit der passenden Plakette hinein; welche, zeigt ein Zusatzzeichen.', A2),
    S('270.2', 'Ende einer Umweltzone', 'vorschrift', 'zone', 'Die Umweltzone endet.', A2),
    S('272', 'Verbot des Wendens', 'vorschrift', 'rund-rot', 'Hier darf nicht gewendet werden.', A2),
    S('273', 'Verbot des Unterschreitens des Mindestabstands', 'vorschrift', 'rund-rot', 'Kfz über 3,5 t und Zugmaschinen dürfen den Abstand (hier 70 m) zu gleichartigen Fahrzeugen nicht unterschreiten. Pkw und Busse sind ausgenommen.', A2),
    S('274', 'Zulässige Höchstgeschwindigkeit', 'vorschrift', 'rund-rot', 'Nicht schneller als angegeben. Außerorts bleiben niedrigere Grenzen für bestimmte Fahrzeuge bestehen, etwa 80 km/h für Pkw mit Anhänger.', A2),
    S('274.1', 'Beginn einer Tempo 30-Zone', 'vorschrift', 'zone', 'In der ganzen Zone höchstens 30 km/h.', A2),
    S('274.2', 'Ende einer Tempo 30-Zone', 'vorschrift', 'zone', 'Die Tempo 30-Zone endet – danach gilt wieder, was sonst angeordnet ist, innerorts meist 50 km/h.', A2),
    S('275', 'Vorgeschriebene Mindestgeschwindigkeit', 'vorschrift', 'rund-blau', 'Nicht langsamer fahren, außer die Verhältnisse zwingen dazu. Fahrzeuge, die so schnell nicht fahren können oder dürfen, dürfen den Streifen nicht benutzen.', A2),
    S('276', 'Überholverbot für Kraftfahrzeuge aller Art', 'vorschrift', 'rund-rot', 'Kraftfahrzeuge dürfen keine mehrspurigen Kraftfahrzeuge und Krafträder mit Beiwagen überholen. Einspurige (Motorräder, Fahrräder) darfst du überholen.', A2),
    S('277', 'Überholverbot für Kraftfahrzeuge über 3,5 t', 'vorschrift', 'rund-rot', 'Gilt für Kfz über 3,5 t und Zugmaschinen – Pkw und Busse sind ausgenommen.', A2),
    S('277.1', 'Verbot des Überholens einspuriger Fahrzeuge', 'vorschrift', 'rund-rot', 'Mehrspurige Kraftfahrzeuge dürfen hier auch Rad- und Motorradfahrer nicht überholen.', A2),
    S('278', 'Ende der zulässigen Höchstgeschwindigkeit', 'vorschrift', 'ende', 'Die angezeigte Geschwindigkeitsbeschränkung endet.', A2),
    S('279', 'Ende der vorgeschriebenen Mindestgeschwindigkeit', 'vorschrift', 'ende', 'Die Mindestgeschwindigkeit gilt nicht mehr.', A2),
    S('280', 'Ende des Überholverbots für Kraftfahrzeuge aller Art', 'vorschrift', 'ende', 'Das Überholverbot aus Zeichen 276 endet.', A2),
    S('281', 'Ende des Überholverbots für Kraftfahrzeuge über 3,5 t', 'vorschrift', 'ende', 'Das Überholverbot aus Zeichen 277 endet.', A2),
    S('281.1', 'Ende des Verbots, einspurige Fahrzeuge zu überholen', 'vorschrift', 'ende', 'Das Verbot aus Zeichen 277.1 endet.', A2),
    S('282', 'Ende sämtlicher Streckenverbote', 'vorschrift', 'ende', 'Alle streckenbezogenen Geschwindigkeitsbeschränkungen und Überholverbote enden.', A2),
    S('283', 'Absolutes Haltverbot', 'vorschrift', 'halt', 'Halten auf der Fahrbahn verboten – auf dieser Straßenseite bis zur nächsten Kreuzung oder Einmündung.', A2),
    S('283-10', 'Absolutes Haltverbot (Anfang)', 'vorschrift', 'halt', 'Ein Pfeil zur Fahrbahn zeigt den Anfang der Verbotsstrecke, ein Pfeil von der Fahrbahn weg ihr Ende. Zwei Pfeilspitzen: Mitte der Strecke.', A2),
    S('286', 'Eingeschränktes Haltverbot', 'vorschrift', 'halt', 'Höchstens drei Minuten halten – ausgenommen zum Ein- oder Aussteigen und zum Be- oder Entladen, das ohne Verzögerung erledigt werden muss.', A2),
    S('290.1', 'Beginn eines eingeschränkten Haltverbots für eine Zone', 'vorschrift', 'zone', 'In der ganzen Zone höchstens drei Minuten halten (außer Ein-/Aussteigen, Be-/Entladen), wenn Schilder nichts anderes regeln.', A2),
    S('290.2', 'Ende eines eingeschränkten Haltverbots für eine Zone', 'vorschrift', 'zone', 'Die Haltverbotszone endet.', A2),

    // Markierungen
    S('293', 'Fußgängerüberweg (Markierung)', 'markierung', 'markierung', 'Zebrastreifen: Fußgängern das Überqueren ermöglichen, wenn nötig warten, nicht überholen (§ 26). Auf dem Überweg und bis 5 m davor nicht halten.', A2),
    S('294', 'Haltlinie', 'markierung', 'markierung', 'Hier anhalten, wenn Zeichen 206, ein Polizist, eine Ampel oder eine Schranke es verlangen.', A2),
    S('295', 'Fahrstreifenbegrenzung', 'markierung', 'markierung', 'Durchgehende Linie: nicht überfahren, auch nicht teilweise. Parken nur, wenn bis zur Linie mindestens 3 m Fahrstreifen bleiben.', A2),
    S('296', 'Einseitige Fahrstreifenbegrenzung', 'markierung', 'markierung', 'Von der Seite der unterbrochenen Linie darfst du hinüber, wenn niemand gefährdet wird – von der Seite der durchgehenden Linie nicht.', A2),
    S('297', 'Pfeilmarkierungen', 'markierung', 'markierung', 'Sind zwischen den Pfeilen Linien markiert, musst du der Pfeilrichtung folgen. Auf der Pfeilstrecke nicht halten. Wer sich eingeordnet hat, darf rechts überholt werden.', A2),
    S('297.1', 'Vorankündigungspfeil', 'markierung', 'markierung', 'Kündigt eine durchgehende Linie oder das Ende eines Fahrstreifens an.', A2),
    S('298', 'Sperrfläche', 'markierung', 'markierung', 'Sperrflächen dürfen nicht benutzt werden – weder zum Fahren noch zum Halten.', A2),
    S('299', 'Grenzmarkierung für Halt- oder Parkverbote', 'markierung', 'markierung', 'Innerhalb der Markierung nicht halten oder parken.', A2),
    S('340', 'Leitlinie', 'markierung', 'markierung', 'Unterbrochene Linie: überfahren erlaubt, wenn dadurch niemand gefährdet wird.', A3),
    S('341', 'Wartelinie', 'markierung', 'markierung', 'Empfiehlt dem Wartepflichtigen, hier zu warten.', A3),
    S('342', 'Haifischzähne', 'markierung', 'markierung', 'Heben eine Wartepflicht hervor, etwa bei rechts vor links abseits von Hauptstraßen. Die Spitzen zeigen zum Wartepflichtigen.', A3),

    // Anlage 3 – Richtzeichen
    S('301', 'Vorfahrt', 'richt', 'dreieck', 'Vorfahrt nur an der nächsten Kreuzung oder Einmündung.', A3),
    S('306', 'Vorfahrtstraße', 'richt', 'sonder', 'Vorfahrt bis zum nächsten Zeichen 205, 206 oder 307. Außerorts auf der Fahrbahn nicht parken.', A3),
    S('307', 'Ende der Vorfahrtstraße', 'richt', 'sonder', 'Die Vorfahrtstraße endet – danach gilt wieder, was Schilder oder Grundregeln sagen.', A3),
    S('308', 'Vorrang vor dem Gegenverkehr', 'richt', 'eckig-blau', 'An der Engstelle hast du Vorrang vor dem Gegenverkehr.', A3),
    S('310', 'Ortstafel (Vorderseite)', 'richt', 'ort', 'Hier beginnt eine geschlossene Ortschaft – die Regeln für innerorts gelten, etwa 50 km/h.', A3),
    S('311', 'Ortstafel (Rückseite)', 'richt', 'ort', 'Hier endet die geschlossene Ortschaft.', A3),
    S('314', 'Parken', 'richt', 'eckig-blau', 'Hier darfst du parken. Zusatzzeichen können Dauer, Fahrzeugart oder Parkschein und Parkscheibe vorschreiben.', A3),
    S('314-50', 'Parkhaus, Parkgarage', 'richt', 'eckig-blau', 'Weist auf ein Parkhaus oder eine Parkgarage hin.', A3),
    S('314.1', 'Beginn einer Parkraumbewirtschaftungszone', 'richt', 'zone', 'In der Zone nur mit Parkschein oder Parkscheibe parken.', A3),
    S('314.2', 'Ende einer Parkraumbewirtschaftungszone', 'richt', 'zone', 'Die Parkraumbewirtschaftungszone endet.', A3),
    S('315', 'Parken auf Gehwegen', 'richt', 'eckig-blau', 'Parken auf dem Gehweg erlaubt – nur bis 2,8 t zulässiger Gesamtmasse und so, wie das Bild die Aufstellung zeigt (hier halb auf dem Gehweg).', A3),
    S('318', 'Parkscheibe', 'richt', 'sonder', 'Wo die Parkscheibe vorgeschrieben ist, stellst du den Zeiger auf den Strich der halben Stunde, die auf deine Ankunft folgt (§ 13 Abs. 2).', A3),
    S('325.1', 'Beginn eines verkehrsberuhigten Bereichs', 'richt', 'eckig-blau', 'Schrittgeschwindigkeit. Fußgänger dürfen die ganze Straße nutzen, Kinderspiele sind überall erlaubt. Parken nur auf gekennzeichneten Flächen.', A3),
    S('325.2', 'Ende eines verkehrsberuhigten Bereichs', 'richt', 'eckig-blau', 'Wer hier ausfährt, muss eine Gefährdung anderer ausschließen – also allen anderen Vorrang lassen (§ 10).', A3),
    S('327', 'Tunnel', 'richt', 'eckig-blau', 'Im Tunnel Abblendlicht einschalten und nicht wenden. Bei einer Panne nur die Nothalte- und Pannenbuchten nutzen.', A3),
    S('328', 'Nothalte- und Pannenbucht', 'richt', 'eckig-blau', 'Nur im Notfall oder bei einer Panne halten.', A3),
    S('330.1', 'Autobahn', 'richt', 'eckig-blau', 'Nur für Kraftfahrzeuge, die bauartbedingt schneller als 60 km/h fahren. Halten, Wenden und Rückwärtsfahren verboten (§ 18).', A3),
    S('330.2', 'Ende der Autobahn', 'richt', 'eckig-blau', 'Die Regeln für Autobahnen gelten nicht mehr.', A3),
    S('331.1', 'Kraftfahrstraße', 'richt', 'eckig-blau', 'Nur für Kfz, die bauartbedingt schneller als 60 km/h fahren. Ein- und Ausfahren nur an Kreuzungen oder Einmündungen, nicht halten, nicht wenden (§ 18).', A3),
    S('331.2', 'Ende der Kraftfahrstraße', 'richt', 'eckig-blau', 'Die Regeln für Kraftfahrstraßen gelten nicht mehr.', A3),
    S('332', 'Ausfahrttafel', 'wegweiser', 'wegweiser', 'Steht an der Autobahnausfahrt und nennt die Ziele. Ausfahren ist nur an so gekennzeichneten Stellen erlaubt (§ 18 Abs. 10).', A3),
    S('333', 'Ausfahrt von der Autobahn', 'wegweiser', 'wegweiser', 'Pfeilschild an der Stelle, wo die Ausfahrt abgeht.', A3),
    S('350', 'Fußgängerüberweg (Hinweis)', 'richt', 'eckig-blau', 'Kündigt einen Zebrastreifen an: Fußgängern das Überqueren ermöglichen, nicht überholen (§ 26).', A3),
    S('350.1', 'Radschnellweg', 'richt', 'eckig-blau', 'Kennzeichnet Beginn und Verlauf eines Radschnellwegs.', A3),
    S('354', 'Wasserschutzgebiet', 'richt', 'eckig-blau', 'Hier liegt ein Wasserschutzgebiet. Laufen nach einem Unfall Öl oder Kraftstoff aus, ist das besonders gefährlich – sofort melden.', A3),
    S('356', 'Verkehrshelfer', 'richt', 'eckig-blau', 'Hier helfen Schülerlotsen oder andere Verkehrshelfer beim Überqueren der Straße.', A3),
    S('357', 'Sackgasse', 'richt', 'eckig-blau', 'Die Straße endet, für Fahrzeuge geht es nicht weiter.', A3),
    S('357-50', 'Sackgasse, für Rad und Fußgänger durchlässig', 'richt', 'eckig-blau', 'Für Autos endet die Straße – Fußgänger und Radfahrer kommen weiter.', A3),
    S('358', 'Erste Hilfe', 'richt', 'eckig-blau', 'Hinweis auf eine Erste-Hilfe-Stelle.', A3),
    S('365-51', 'Notrufsäule', 'richt', 'eckig-blau', 'Hinweis auf eine Notrufsäule.', A3),
    S('365-65', 'Ladestation für Elektrofahrzeuge', 'richt', 'eckig-blau', 'Hinweis auf eine Ladesäule für E-Autos.', A3),
    S('390', 'Mautpflicht', 'richt', 'eckig-blau', 'Ab hier gilt die Maut nach dem Bundesfernstraßenmautgesetz.', A3),
    S('394', 'Laternenring', 'richt', 'sonder', 'Diese Laterne leuchtet nicht die ganze Nacht. Wer dort parkt, muss sein Fahrzeug dann selbst beleuchten (§ 17 Abs. 4).', A3),

    // Wegweisung und Umleitung
    S('401', 'Nummernschild für Bundesstraßen', 'wegweiser', 'wegweiser', 'Gelbes Schild mit schwarzer Nummer: Bundesstraße.', A3),
    S('405', 'Nummernschild für Autobahnen', 'wegweiser', 'wegweiser', 'Blaues Schild mit weißer Nummer: Autobahn.', A3),
    S('406', 'Nummer eines Autobahn-Knotenpunkts', 'wegweiser', 'wegweiser', 'Laufende Nummer der Ausfahrten, Kreuze und Dreiecke der Autobahn, auf der du fährst.', A3),
    S('410', 'Nummernschild für Europastraßen', 'wegweiser', 'wegweiser', 'Grünes Schild mit weißer Nummer: Europastraße.', A3),
    S('415', 'Pfeilwegweiser auf Bundesstraßen', 'wegweiser', 'wegweiser', 'Gelber Pfeilwegweiser an Bundesstraßen – die Nummer der Bundesstraße steht mit darauf.', A3),
    S('418', 'Pfeilwegweiser auf sonstigen Straßen', 'wegweiser', 'wegweiser', 'Gelber Pfeilwegweiser an anderen Straßen mit größerer Verkehrsbedeutung.', A3),
    S('419', 'Pfeilwegweiser für Straßen geringerer Bedeutung', 'wegweiser', 'wegweiser', 'Kleinerer gelber Pfeilwegweiser an Straßen mit geringerer Verkehrsbedeutung.', A3),
    S('421', 'Pfeilwegweiser für bestimmte Verkehrsarten', 'wegweiser', 'wegweiser', 'Gilt nur für die gezeigte Verkehrsart, hier Kfz über 3,5 t.', A3),
    S('430', 'Pfeilwegweiser zur Autobahn', 'wegweiser', 'wegweiser', 'Blauer Wegweiser: Hier geht es zur Autobahn.', A3),
    S('432', 'Pfeilwegweiser zu innerörtlichen Zielen', 'wegweiser', 'wegweiser', 'Weißer Wegweiser zu Zielen innerhalb des Ortes und zu wichtigen Einrichtungen, etwa zum Bahnhof.', A3),
    S('434', 'Tabellenwegweiser', 'wegweiser', 'wegweiser', 'Zeigt mehrere Ziele und Richtungen auf einer Tafel.', A3),
    S('437', 'Straßennamensschild', 'wegweiser', 'wegweiser', 'Nennt den Namen der Straße.', A3),
    S('438', 'Vorwegweiser', 'wegweiser', 'wegweiser', 'Kündigt vor einer Kreuzung außerhalb der Autobahn an, welche Richtung wohin führt.', A3),
    S('440', 'Vorwegweiser zur Autobahn', 'wegweiser', 'wegweiser', 'Kündigt vor einer Kreuzung an, wo es zur Autobahn geht.', A3),
    S('448', 'Ankündigungstafel auf der Autobahn', 'wegweiser', 'wegweiser', 'Kündigt eine Ausfahrt, ein Autobahnkreuz oder ein Autobahndreieck an, mit dessen Nummer.', A3),
    S('449', 'Vorwegweiser auf der Autobahn', 'wegweiser', 'wegweiser', 'Zeigt vor einer Ausfahrt oder einem Kreuz, welche Fahrstreifen wohin führen.', A3),
    S('450-51', 'Ankündigungsbake (200 m)', 'wegweiser', 'bake', 'Steht 300 m (drei Streifen), 200 m (zwei Streifen, wie hier) und 100 m (ein Streifen) vor einer Autobahnausfahrt, einem Kreuz oder Dreieck.', A3),
    S('453', 'Entfernungstafel', 'wegweiser', 'wegweiser', 'Nennt Fernziele und die Entfernung bis zur Ortsmitte. Ziele unter dem Strich erreicht man über eine andere Autobahn.', A3),
    S('454', 'Umleitungswegweiser', 'wegweiser', 'wegweiser', 'Führt eine vorübergehende Umleitung, zum Beispiel wegen einer Baustelle.', A3),
    S('455.1', 'Ankündigung oder Fortsetzung der Umleitung', 'wegweiser', 'wegweiser', 'Kündigt eine Umleitung an oder zeigt, wie sie weitergeht.', A3),
    S('457.1', 'Umleitungsankündigung', 'wegweiser', 'wegweiser', 'Kündigt eine Umleitung an, mit Entfernung auf einem Zusatzzeichen.', A3),
    S('460', 'Bedarfsumleitung', 'wegweiser', 'wegweiser', 'Kennzeichnet eine Ausweichstrecke zwischen zwei Autobahnanschlussstellen, etwa bei Stau.', A3),
    S('467.1', 'Umlenkungspfeil', 'wegweiser', 'wegweiser', 'Empfohlene Ausweichstrecke auf Autobahnen, die bei Bedarf genutzt werden soll.', A3),
    S('501', 'Überleitungstafel', 'wegweiser', 'wegweiser', 'Kündigt die Überleitung des Verkehrs auf die Gegenfahrbahn an, etwa vor einer Baustelle.', A3),
    S('531', 'Einengungstafel', 'wegweiser', 'wegweiser', 'Zeigt, dass ein Fahrstreifen wegfällt – rechtzeitig einordnen, im Reißverschlussverfahren (§ 7 Abs. 4).', A3),

    // Anlage 4 – Verkehrseinrichtungen
    S('600', 'Absperrschranke', 'einrichtung', 'einrichtung', 'Die abgesperrte Fläche darf nicht befahren werden. Rote Warnleuchten: ganze Fahrbahn gesperrt, sonst gelb.', A4),
    S('605', 'Leitbake', 'einrichtung', 'einrichtung', 'Leitet den Verkehr an einer gesperrten Fläche vorbei. Die Streifen fallen zu der Seite ab, an der du vorbeifährst.', A4),
    S('610', 'Leitkegel', 'einrichtung', 'einrichtung', 'Sperrt eine Fläche ab und leitet den Verkehr daran vorbei.', A4),
    S('615', 'Fahrbare Absperrtafel', 'einrichtung', 'einrichtung', 'Sichert eine Arbeitsstelle ab. Die abgesperrte Fläche darf nicht befahren werden.', A4),
    S('616', 'Fahrbare Absperrtafel mit Blinkpfeil', 'einrichtung', 'einrichtung', 'Sperrt einen Fahrstreifen, der Blinkpfeil zeigt, wohin du ausweichen musst.', A4),
    S('620-40', 'Leitpfosten (rechts)', 'einrichtung', 'einrichtung', 'Machen den Straßenverlauf sichtbar. Sie stehen in der Regel alle 50 m, in Kurven dichter.', A4),
    S('625', 'Richtungstafel in Kurven', 'einrichtung', 'einrichtung', 'Zeigt den Verlauf einer Kurve an.', A4),
    S('626', 'Leitplatte', 'einrichtung', 'einrichtung', 'Kennzeichnet ein dauerhaftes Hindernis. Die Schraffen fallen zu der Seite ab, an der du vorbeifährst.', A4),
    S('630', 'Parkwarntafel', 'einrichtung', 'einrichtung', 'Kennzeichnet abgestellte Fahrzeuge und Anhänger bei Dunkelheit.', A4),

    // Ampeln, Polizei und Bahnübergänge
    S('l-rot', 'Ampel: Rot', 'licht', 'licht', 'Halt vor der Kreuzung.', 'StVO § 37 Abs. 2', null),
    S('l-rotgelb', 'Ampel: Rot und Gelb', 'licht', 'licht', 'Als Nächstes kommt Grün – bis dahin weiter warten. Die Farbfolge ist Grün – Gelb – Rot – Rot und Gelb – Grün.', 'StVO § 37 Abs. 2', null),
    S('l-gelb', 'Ampel: Gelb', 'licht', 'licht', 'Vor der Kreuzung auf das nächste Zeichen warten.', 'StVO § 37 Abs. 2', null),
    S('l-gruen', 'Ampel: Grün', 'licht', 'licht', 'Der Verkehr ist freigegeben. Abbiegen nach den Regeln des § 9 – Gegenverkehr und Fußgänger beachten.', 'StVO § 37 Abs. 2', null),
    S('l-pfeil', 'Ampel: grüner Pfeil', 'licht', 'licht', 'Nur in Pfeilrichtung ist der Verkehr freigegeben. Ein grüner Pfeil nach links heißt: Der Gegenverkehr steht, du kannst ungehindert abbiegen.', 'StVO § 37 Abs. 2', null),
    S('720', 'Grünpfeilschild', 'licht', 'licht', 'Nach dem Anhalten darfst du bei Rot rechts abbiegen – nur aus dem rechten Fahrstreifen und ohne Fußgänger oder den freigegebenen Verkehr zu behindern.', 'StVO § 37 Abs. 2'),
    S('721', 'Grünpfeil nur für Radverkehr', 'licht', 'licht', 'Der Grünpfeil gilt nur für Radfahrer.', 'StVO § 37 Abs. 2'),
    S('l-kreuz', 'Dauerlicht: rote gekreuzte Balken', 'licht', 'licht', 'Dieser Fahrstreifen darf nicht benutzt werden.', 'StVO § 37 Abs. 3', null),
    S('l-runter', 'Dauerlicht: grüner Pfeil nach unten', 'licht', 'licht', 'Der Fahrstreifen ist freigegeben.', 'StVO § 37 Abs. 3', null),
    S('l-schraeg', 'Dauerlicht: gelb blinkender Schrägpfeil', 'licht', 'licht', 'Fahrstreifen in Pfeilrichtung wechseln.', 'StVO § 37 Abs. 3', null),
    S('l-polizei-seite', 'Polizist: Arme seitlich ausgestreckt', 'licht', 'licht', 'Quer zu deiner Fahrtrichtung: Halt vor der Kreuzung. Der Querverkehr ist freigegeben.', 'StVO § 36 Abs. 2', null),
    S('l-polizei-hoch', 'Polizist: Arm hochgehoben', 'licht', 'licht', 'Vor der Kreuzung auf das nächste Zeichen warten. Wer schon in der Kreuzung ist, räumt sie.', 'StVO § 36 Abs. 2', null),
    S('l-blau', 'Blaues Blinklicht mit Einsatzhorn', 'licht', 'licht', 'Alle anderen schaffen sofort freie Bahn.', 'StVO § 38 Abs. 1', null),
    S('l-gelbblink', 'Gelbes Blinklicht', 'licht', 'licht', 'Warnt vor Gefahren, etwa vor Arbeits- oder Unfallstellen oder sehr langsamen Fahrzeugen.', 'StVO § 38 Abs. 3', null),
    S('bue-licht', 'Lichtzeichen am Bahnübergang', 'licht', 'licht', 'Gelb oder Rot: vor dem Andreaskreuz warten.', 'StVO § 19 Abs. 2', null),
    S('bue-halbschranke', 'Rotes Blinklicht mit Halbschranke', 'licht', 'licht', 'Blinkt es rot oder senkt sich die Schranke, vor dem Andreaskreuz warten.', 'StVO § 19 Abs. 2', null),

    // Zusatzzeichen
    S('1000-10', 'Richtung (linksweisend)', 'zusatz', 'zusatz', 'Das Zeichen darüber gilt in Pfeilrichtung, hier nach links.', VZ),
    S('1000-11', 'Vorankündigung (linksweisend)', 'zusatz', 'zusatz', 'Die angezeigte Gefahr liegt in der Straße in Pfeilrichtung (§ 40 Abs. 5).', VZ),
    S('1000-30', 'Beide Richtungen', 'zusatz', 'zusatz', 'Gilt in beide Richtungen.', VZ),
    S('1000-32', 'Radverkehr kreuzt von links und rechts', 'zusatz', 'zusatz', 'Mit Zeichen 205 oder 206: Vorfahrt gewähren und dabei auf Radfahrer und E-Scooter von links und rechts achten.', A2),
    S('1001-30', 'Länge einer Strecke (auf 800 m)', 'zusatz', 'zusatz', 'So lang ist die Gefahrstrecke oder das Verbot.', '§ 40 Abs. 4'),
    S('1001-32', 'Restlänge (noch 500 m)', 'zusatz', 'zusatz', 'Die Strecke oder das Verbot gilt noch so weit.', VZ),
    S('1002-10', 'Abknickende Vorfahrt (Kreuzung)', 'zusatz', 'zusatz', 'Zeigt den Verlauf der Vorfahrtstraße (dicke Linie). Wer ihr folgt, muss blinken. Auf Fußgänger besonders achten.', A3),
    S('1002-12', 'Abknickende Vorfahrt (Einmündung)', 'zusatz', 'zusatz', 'Wie an Kreuzungen – hier an einer Einmündung.', A3),
    S('1004-30', 'Entfernung (nach 100 m)', 'zusatz', 'zusatz', 'Die Gefahrstelle oder Anordnung beginnt erst nach dieser Entfernung.', '§ 40 Abs. 2, § 41 Abs. 2'),
    S('1004-32', 'Halt in 100 m', 'zusatz', 'zusatz', 'Kündigt zusammen mit Zeichen 205 ein Haltgebot (Zeichen 206) in der angegebenen Entfernung an.', A2),
    S('1005-30', 'Reißverschluss erst in 200 m', 'zusatz', 'zusatz', 'Weiterfahren und erst unmittelbar vor der Engstelle abwechselnd einfädeln (§ 7 Abs. 4).', VZ),
    S('1006-31', 'Unfallgefahr', 'zusatz', 'zusatz', 'Hier passieren besonders häufig Unfälle.', VZ),
    S('1007-30', 'Ölspur', 'zusatz', 'zusatz', 'Öl auf der Fahrbahn – Rutschgefahr.', VZ),
    S('1007-32', 'Rollsplitt', 'zusatz', 'zusatz', 'Loser Splitt auf der Fahrbahn.', VZ),
    S('1007-35', 'Verschmutzte Fahrbahn', 'zusatz', 'zusatz', 'Die Fahrbahn ist verschmutzt, zum Beispiel durch Erde.', VZ),
    S('1007-50', 'Unfall', 'zusatz', 'zusatz', 'Eine Unfallstelle folgt.', VZ),
    S('1007-61', 'Nebel', 'zusatz', 'zusatz', 'Mit Nebel rechnen. Sichtweite unter 50 m: höchstens 50 km/h, dann ist die Nebelschlussleuchte erlaubt.', '§ 3, § 17'),
    S('1008-30', 'Vorfahrt geändert', 'zusatz', 'zusatz', 'Die Vorfahrtsregelung ist neu – besonders aufmerksam sein.', VZ),
    S('1008-32', 'Industriegebiet – Schienenfahrzeuge haben Vorrang', 'zusatz', 'zusatz', 'Mit dem Andreaskreuz an den Einfahrten: Im ganzen Gebiet haben Bahnen Vorrang.', '§ 19 Abs. 1'),
    S('1010-10', 'Kinder dürfen spielen', 'zusatz', 'zusatz', 'Kinder dürfen auch auf der Fahrbahn und dem Seitenstreifen spielen.', VZ),
    S('1010-12', 'Anhänger länger als 14 Tage', 'zusatz', 'zusatz', 'Auf dieser Parkfläche dürfen Anhänger auch länger als zwei Wochen stehen (sonst verboten, § 12 Abs. 3b).', VZ),
    S('1010-52', 'Radverkehr', 'zusatz', 'zusatz', 'Das Zeichen darüber gilt nur für Radfahrer.', VZ),
    S('1010-56', 'Straßenbahn', 'zusatz', 'zusatz', 'Mit Zeichen 205: der Straßenbahn Vorfahrt gewähren.', A2),
    S('1010-68', 'E-Scooter', 'zusatz', 'zusatz', 'Das Zeichen darüber gilt nur für Elektrokleinstfahrzeuge.', VZ),
    S('1012-30', 'Ladezone', 'zusatz', 'zusatz', 'Kennzeichnet eine Ladezone.', VZ),
    S('1012-31', 'Ende', 'zusatz', 'zusatz', 'Hier endet die Anordnung des Zeichens darüber.', VZ),
    S('1012-32', 'Radfahrer absteigen', 'zusatz', 'zusatz', 'Radfahrer müssen absteigen und schieben.', VZ),
    S('1012-50', 'Schule', 'zusatz', 'zusatz', 'Hinweis auf eine Schule – mit Kindern rechnen.', VZ),
    S('1020-30', 'Anlieger frei', 'zusatz', 'zusatz', 'Wer dort ein Ziel hat (Anlieger, Besuch, Lieferung), darf trotz des Verbots darüber fahren.', VZ),
    S('1020-31', 'Anlieger oder Parken frei', 'zusatz', 'zusatz', 'Anlieger und wer dort parken will, dürfen trotz des Verbots fahren.', VZ),
    S('1020-32', 'Bewohner mit Parkausweis frei', 'zusatz', 'zusatz', 'Bewohner mit dem genannten Parkausweis sind von der Anordnung ausgenommen.', A2),
    S('1022-10', 'Radverkehr frei', 'zusatz', 'zusatz', 'Radfahrer dürfen trotz des Zeichens darüber fahren – mit Zeichen 267 zum Beispiel einfahren.', A2),
    S('1022-11', 'Mofas frei', 'zusatz', 'zusatz', 'Mofas sind vom Verbot ausgenommen.', VZ),
    S('1024-10', 'Personenkraftwagen frei', 'zusatz', 'zusatz', 'Pkw sind vom Verbot ausgenommen.', VZ),
    S('1026-30', 'Taxi frei', 'zusatz', 'zusatz', 'Taxen sind ausgenommen, etwa auf einem Busstreifen.', A2),
    S('1026-32', 'Linienverkehr frei', 'zusatz', 'zusatz', 'Linienbusse sind vom Verbot ausgenommen.', VZ),
    S('1026-35', 'Lieferverkehr frei', 'zusatz', 'zusatz', 'Wer Waren bringt oder abholt, darf trotz des Verbots fahren.', VZ),
    S('1031-52', 'Freistellung für grüne Plakette', 'zusatz', 'zusatz', 'Mit Zeichen 270.1: Fahrzeuge mit grüner Plakette dürfen in die Umweltzone.', A2),
    S('1040-30', 'Zeitliche Beschränkung (16–18 h)', 'zusatz', 'zusatz', 'Das Zeichen darüber gilt nur von 16 bis 18 Uhr.', VZ),
    S('1040-32', 'Parkscheibe 2 Stunden', 'zusatz', 'zusatz', 'Parken mit Parkscheibe, höchstens 2 Stunden.', A3),
    S('1042-30', 'werktags', 'zusatz', 'zusatz', 'Gilt nur an Werktagen – dazu zählt auch der Samstag.', VZ),
    S('1042-36', 'Schulbus (mit Uhrzeit)', 'zusatz', 'zusatz', 'Mit Zeichen 224: Haltestelle nur für Schulbusse, zu den angegebenen Zeiten.', A2),
    S('1044-30', 'Bewohner mit Parkausweis', 'zusatz', 'zusatz', 'Mit Zeichen 314: Parken nur für Bewohner mit dem genannten Parkausweis.', A3),
    S('1049-11', 'Langsame Fahrzeuge dürfen überholt werden', 'zusatz', 'zusatz', 'Trotz Überholverbot dürfen Fahrzeuge überholt werden, die nicht schneller als 25 km/h fahren können oder dürfen, etwa Traktoren.', VZ),
    S('1053-30', 'Parken in gekennzeichneten Flächen', 'zusatz', 'zusatz', 'Parken nur innerhalb der markierten Flächen erlaubt.', VZ),
    S('1053-31', 'mit Parkschein', 'zusatz', 'zusatz', 'Parken nur mit Parkschein, gut lesbar ausgelegt.', A3),
    S('1053-32', 'gebührenpflichtig', 'zusatz', 'zusatz', 'Das Parken kostet Gebühren.', A3),
    S('1053-33', 'Massenangabe 7,5 t', 'zusatz', 'zusatz', 'Das Verbot darüber gilt nur für Fahrzeuge, deren zulässige Gesamtmasse (mit Anhänger) 7,5 t übersteigt.', A2),
    S('1053-34', 'auf dem Seitenstreifen', 'zusatz', 'zusatz', 'Mit Zeichen 283 oder 286: Das Haltverbot gilt nur auf dem Seitenstreifen.', A2),
    S('1053-35', 'bei Nässe', 'zusatz', 'zusatz', 'Mit Zeichen 274: Die Höchstgeschwindigkeit gilt bei nasser Fahrbahn.', A2),
    S('1060-31', 'Haltverbot auch auf dem Seitenstreifen', 'zusatz', 'zusatz', 'Mit Zeichen 283 oder 286: Das Haltverbot gilt auch auf dem Seitenstreifen.', A2),
    S('1060-33', 'Massenangabe 2,8 t', 'zusatz', 'zusatz', 'Mit Zeichen 277: Das Überholverbot gilt schon für Kraftfahrzeuge über 2,8 t.', A2)
  ];

  /* ---------- Zahlen und Regeln ----------
     typ 'zahl': antwort (Zahl), einheit; typ 'wahl': optionen, richtig (Index) */
  const THEMEN = [
    { id: 'tempo', name: 'Geschwindigkeit' },
    { id: 'abstand', name: 'Abstand und Überholen' },
    { id: 'parken', name: 'Halten und Parken' },
    { id: 'vorfahrt', name: 'Vorfahrt und Vorrang' },
    { id: 'sicher', name: 'Licht, Panne, Sicherheit' },
    { id: 'person', name: 'Fahrer und Führerschein' }
  ];
  const Z = (id, thema, frage, antwort, einheit, erklaerung, quelle) => ({ id, thema, typ: 'zahl', frage, antwort, einheit, erklaerung, quelle });
  const Wa = (id, thema, frage, optionen, richtig, erklaerung, quelle) => ({ id, thema, typ: 'wahl', frage, optionen, richtig, erklaerung, quelle });

  const FAKTEN = [
    Z('t-innerorts', 'tempo', 'Höchstgeschwindigkeit innerorts für alle Kraftfahrzeuge?', 50, 'km/h', 'Gilt auch unter günstigsten Umständen, solange kein Schild mehr erlaubt.', 'StVO § 3 Abs. 3 Nr. 1'),
    Z('t-pkw-ausserorts', 'tempo', 'Höchstgeschwindigkeit für Pkw außerorts (nicht Autobahn)?', 100, 'km/h', 'Gilt nicht auf Autobahnen, auf Straßen mit baulich getrennten Richtungsfahrbahnen und auf Straßen mit mindestens zwei markierten Fahrstreifen je Richtung.', 'StVO § 3 Abs. 3 Nr. 2c'),
    Z('t-anhaenger', 'tempo', 'Höchstgeschwindigkeit für Pkw mit Anhänger außerorts?', 80, 'km/h', 'Gilt außerorts und auf der Autobahn. Mit einer Tempo-100-Zulassung des Gespanns sind auf der Autobahn bis 100 km/h erlaubt.', 'StVO § 3 Abs. 3 Nr. 2a, § 18 Abs. 5'),
    Z('t-ketten', 'tempo', 'Höchstgeschwindigkeit mit Schneeketten?', 50, 'km/h', 'Gilt auch unter günstigsten Umständen.', 'StVO § 3 Abs. 4'),
    Z('t-nebel', 'tempo', 'Sichtweite wegen Nebel, Schnee oder Regen unter 50 m: Wie schnell darfst du höchstens fahren?', 50, 'km/h', 'Oft ist sogar langsamer geboten – du musst innerhalb der übersehbaren Strecke halten können.', 'StVO § 3 Abs. 1'),
    Z('t-autobahn-min', 'tempo', 'Autobahn und Kraftfahrstraße: Wie schnell muss ein Kfz bauartbedingt mehr als fahren können?', 60, 'km/h', 'Das gilt auch für mitgeführte Anhänger.', 'StVO § 18 Abs. 1'),
    Z('t-richt', 'tempo', 'Richtgeschwindigkeit auf der Autobahn?', 130, 'km/h', 'Eine Empfehlung, keine Pflicht. Wer schneller fährt, dem kann bei einem Unfall eine Mithaftung drohen.', 'Autobahn-Richtgeschwindigkeits-Verordnung'),
    Z('t-fahrradstrasse', 'tempo', 'Höchstgeschwindigkeit in einer Fahrradstraße?', 30, 'km/h', 'Radfahrer dürfen dort weder gefährdet noch behindert werden, wenn nötig noch langsamer fahren.', 'StVO Anlage 2 Nr. 23'),
    Wa('t-berueh', 'tempo', 'Wie schnell darfst du im verkehrsberuhigten Bereich (Zeichen 325.1) fahren?', ['Schrittgeschwindigkeit', '20 km/h', '30 km/h'], 0, 'Fußgänger dürfen dort die ganze Straße benutzen, Kinder überall spielen.', 'StVO Anlage 3 Nr. 12'),
    Wa('t-lkw35', 'tempo', 'Welche Höchstgeschwindigkeit gilt außerorts für Kfz über 3,5 t bis 7,5 t (keine Pkw)?', ['60 km/h', '80 km/h', '100 km/h'], 1, 'Dasselbe gilt für Pkw mit Anhänger und Lkw bis 3,5 t mit Anhänger.', 'StVO § 3 Abs. 3 Nr. 2a'),
    Wa('t-274-aussen', 'tempo', 'Außerorts zeigt ein Schild 120 km/h. Du fährst Pkw mit Anhänger. Was gilt?', ['120 km/h', '100 km/h', '80 km/h'], 2, 'Ein Schild mit höherer Geschwindigkeit hebt die Grenzen für bestimmte Fahrzeugarten außerorts nicht auf.', 'StVO Anlage 2 Nr. 49'),

    Z('a-rad-innen', 'abstand', 'Mindest-Seitenabstand innerorts beim Überholen von Radfahrern, Fußgängern und E-Scootern?', 1.5, 'm', 'Außerorts sind es mindestens 2 m.', 'StVO § 5 Abs. 4'),
    Z('a-rad-aussen', 'abstand', 'Mindest-Seitenabstand außerorts beim Überholen von Radfahrern?', 2, 'm', 'Innerorts sind es mindestens 1,5 m.', 'StVO § 5 Abs. 4'),
    Z('a-lkw-ab', 'abstand', 'Lkw über 3,5 t auf der Autobahn bei mehr als 50 km/h: Mindestabstand zum Vordermann?', 50, 'm', 'Gilt auch für Busse.', 'StVO § 4 Abs. 3'),
    Wa('a-links-ab', 'abstand', 'Ein Fahrzeug vor dir hat links geblinkt und sich zur Mitte eingeordnet. Wie überholst du?', ['Rechts', 'Links', 'Gar nicht'], 0, 'Wer seine Absicht angekündigt und sich eingeordnet hat, ist rechts zu überholen.', 'StVO § 5 Abs. 7'),
    Wa('a-tram', 'abstand', 'Auf welcher Seite überholst du eine fahrende Straßenbahn in der Regel?', ['Rechts', 'Links', 'Beliebig'], 0, 'Links nur, wenn die Schienen zu weit rechts liegen, oder auf Fahrbahnen für eine Richtung.', 'StVO § 5 Abs. 7'),
    Wa('a-ueberholt', 'abstand', 'Du wirst überholt. Was darfst du nicht?', ['Schneller werden', 'Rechts bleiben', 'Gleichmäßig weiterfahren'], 0, 'Wer überholt wird, darf seine Geschwindigkeit nicht erhöhen.', 'StVO § 5 Abs. 6'),
    Wa('a-ankuendigen', 'abstand', 'Womit darfst du das Überholen außerorts ankündigen?', ['Kurzes Hupen oder Lichthupe', 'Nur Blinker links', 'Warnblinker'], 0, 'Außerorts sind kurze Schall- oder Leuchtzeichen erlaubt; entgegenkommende Fahrer dürfen nicht geblendet werden. Blinken musst du trotzdem.', 'StVO § 5 Abs. 4a und 5'),
    Wa('a-bahn', 'abstand', 'Ab wo gilt vor einem Bahnübergang mit Andreaskreuz das Überholverbot für Kraftfahrzeuge?', ['Ab Zeichen 151 bzw. 156', 'Erst am Andreaskreuz', 'Nur bei geschlossener Schranke'], 0, 'Es gilt bis einschließlich des Kreuzungsbereichs von Schiene und Straße.', 'StVO § 19 Abs. 1'),
    Wa('a-zebra', 'abstand', 'Darfst du an einem Fußgängerüberweg überholen?', ['Nein', 'Ja, wenn niemand zu sehen ist', 'Nur Radfahrer'], 0, 'An Überwegen darf nicht überholt werden.', 'StVO § 26 Abs. 3'),
    Wa('a-bus-warn', 'abstand', 'Ein Linienbus nähert sich mit Warnblinklicht einer Haltestelle. Was gilt?', ['Nicht überholen', 'Zügig überholen', 'Hupen und vorbeifahren'], 0, 'Hält er dann mit Warnblinklicht, darfst du nur mit Schrittgeschwindigkeit vorbeifahren – auch der Gegenverkehr.', 'StVO § 20 Abs. 3 und 4'),

    Z('p-3min', 'parken', 'Ab wie vielen Minuten Halten parkst du?', 3, 'min', 'Wer länger als drei Minuten hält oder sein Fahrzeug verlässt, parkt.', 'StVO § 12 Abs. 2'),
    Z('p-kreuzung', 'parken', 'Wie weit vor und hinter Kreuzungen und Einmündungen darfst du nicht parken?', 5, 'm', 'Gemessen ab den Schnittpunkten der Fahrbahnkanten. Ist rechts ein baulicher Radweg, sind es vor der Kreuzung 8 m.', 'StVO § 12 Abs. 3 Nr. 1'),
    Z('p-kreuzung-rad', 'parken', 'Rechts neben der Fahrbahn verläuft ein baulich angelegter Radweg. Wie weit vor einer Kreuzung gilt dann das Parkverbot?', 8, 'm', 'Sonst sind es 5 m vor und hinter der Kreuzung.', 'StVO § 12 Abs. 3 Nr. 1'),
    Z('p-haltestelle', 'parken', 'Parkverbot vor und hinter einer Haltestelle (Zeichen 224)?', 15, 'm', 'Jeweils vor und hinter dem Zeichen.', 'StVO Anlage 2 Nr. 14'),
    Z('p-zebra', 'parken', 'Bis wie viele Meter vor einem Fußgängerüberweg darfst du nicht halten?', 5, 'm', 'Auf dem Überweg selbst natürlich auch nicht.', 'StVO Anlage 2 Nr. 66'),
    Z('p-ampel', 'parken', 'Bis wie viele Meter vor einer Ampel darfst du nicht halten, wenn sie dadurch verdeckt wird?', 10, 'm', 'Dasselbe gilt vor den Zeichen 201, 205 und 206.', 'StVO § 37 Abs. 1'),
    Z('p-andreas-innen', 'parken', 'Andreaskreuz innerorts: Parkverbot bis wie viele Meter davor und dahinter?', 5, 'm', 'Außerorts sind es 50 m.', 'StVO Anlage 2 Nr. 1'),
    Z('p-andreas-aussen', 'parken', 'Andreaskreuz außerorts: Parkverbot bis wie viele Meter davor und dahinter?', 50, 'm', 'Innerorts sind es 5 m.', 'StVO Anlage 2 Nr. 1'),
    Z('p-3m', 'parken', 'Wie breit muss der Fahrstreifen zwischen deinem geparkten Auto und einer durchgezogenen Linie mindestens bleiben?', 3, 'm', 'Sonst darfst du dort nicht parken.', 'StVO Anlage 2 Nr. 68'),
    Z('p-gehweg', 'parken', 'Bis zu welcher zulässigen Gesamtmasse darf man auf Gehwegen parken, wo es erlaubt ist?', 2.8, 't', 'Gilt für Zeichen 315 und für Parkflächenmarkierungen auf Gehwegen.', 'StVO Anlage 3 Nr. 10, Anlage 2 Nr. 74'),
    Wa('p-anhaenger', 'parken', 'Wie lange darf ein Anhänger ohne Zugfahrzeug höchstens geparkt werden?', ['Zwei Wochen', 'Eine Woche', 'Unbegrenzt'], 0, 'Außer auf entsprechend gekennzeichneten Parkplätzen.', 'StVO § 12 Abs. 3b'),
    Wa('p-286', 'parken', 'Was darfst du beim eingeschränkten Haltverbot (Zeichen 286) länger als drei Minuten?', ['Ein- und Aussteigen oder Be- und Entladen', 'Kurz einkaufen gehen', 'Auf jemanden warten'], 0, 'Ladegeschäfte müssen ohne Verzögerung erledigt werden.', 'StVO Anlage 2 Nr. 63'),
    Wa('p-306', 'parken', 'Wo ist das Parken auf der Fahrbahn einer Vorfahrtstraße verboten?', ['Außerorts', 'Innerorts', 'Überall'], 0, 'Innerorts ist es nicht durch Zeichen 306 verboten.', 'StVO Anlage 3 Nr. 2'),
    Wa('p-seite', 'parken', 'Auf welcher Seite darfst du in einer Einbahnstraße parken?', ['Rechts und links', 'Nur rechts', 'Nur links'], 0, 'Sonst ist rechts zu parken, außer rechts liegen Schienen.', 'StVO § 12 Abs. 4'),
    Wa('p-luecke', 'parken', 'Wer hat Vorrang an einer Parklücke?', ['Wer sie zuerst unmittelbar erreicht', 'Wer schneller einparkt', 'Das größere Fahrzeug'], 0, 'Der Vorrang bleibt, wenn man vorbeifährt, um rückwärts einzuparken.', 'StVO § 12 Abs. 5'),

    Wa('v-rangfolge', 'vorfahrt', 'Was gilt zuerst?', ['Zeichen eines Polizisten', 'Ampel', 'Vorfahrtschild'], 0, 'Reihenfolge: Polizei vor Ampel vor Verkehrszeichen vor Grundregeln wie rechts vor links.', 'StVO § 36 Abs. 1, § 37 Abs. 1, § 39 Abs. 2'),
    Wa('v-ampel-schild', 'vorfahrt', 'Die Ampel zeigt Grün, dein Schild zeigt „Vorfahrt gewähren“. Was gilt?', ['Die Ampel', 'Das Schild', 'Rechts vor links'], 0, 'Lichtzeichen gehen Vorrangregeln und Vorfahrtschildern vor. Fällt die Ampel aus, gilt das Schild.', 'StVO § 37 Abs. 1'),
    Wa('v-feldweg', 'vorfahrt', 'Du kommst aus einem Feldweg von rechts auf eine Straße. Hast du Vorfahrt?', ['Nein', 'Ja, rechts vor links', 'Nur mit Blinker'], 0, 'Rechts vor links gilt nicht für Fahrzeuge aus Feld- oder Waldwegen.', 'StVO § 8 Abs. 1 Nr. 2'),
    Wa('v-kreis', 'vorfahrt', 'Kreisverkehr mit Zeichen 215 unter Zeichen 205: Was gilt beim Einfahren?', ['Nicht blinken, Verkehr im Kreis hat Vorfahrt', 'Rechts blinken, du hast Vorfahrt', 'Links blinken'], 0, 'Beim Ausfahren blinkst du rechts.', 'StVO § 8 Abs. 1a'),
    Wa('v-grundstueck', 'vorfahrt', 'Du fährst aus einer Grundstückseinfahrt auf die Straße. Was gilt?', ['Du musst eine Gefährdung anderer ausschließen', 'Rechts vor links', 'Wer zuerst da ist'], 0, 'Wenn nötig, lässt du dich einweisen. Dasselbe gilt beim Ausfahren aus einem verkehrsberuhigten Bereich.', 'StVO § 10'),
    Wa('v-linkslinks', 'vorfahrt', 'Zwei Fahrzeuge kommen sich entgegen und wollen beide links abbiegen. Wie?', ['Voreinander abbiegen', 'Umeinander herum abbiegen', 'Wer zuerst blinkt, fährt'], 0, 'Außer Verkehrslage oder Kreuzung erfordern, erst aneinander vorbeizufahren.', 'StVO § 9 Abs. 4'),
    Wa('v-links-rechts', 'vorfahrt', 'Du willst links abbiegen, der Gegenverkehr rechts. Wer fährt zuerst?', ['Der Gegenverkehr', 'Du', 'Gleichzeitig'], 0, 'Linksabbieger müssen entgegenkommende Rechtsabbieger durchfahren lassen.', 'StVO § 9 Abs. 4'),
    Wa('v-rad-rechts', 'vorfahrt', 'Du biegst rechts ab, neben dir fährt ein Radfahrer geradeaus. Was gilt?', ['Radfahrer durchfahren lassen', 'Du hast Vorrang', 'Hupen und abbiegen'], 0, 'Beim Abbiegen musst du Radfahrer, E-Scooter und Schienenfahrzeuge in gleicher Richtung durchlassen und auf Fußgänger besonders achten.', 'StVO § 9 Abs. 3'),
    Wa('v-blaulicht', 'vorfahrt', 'Ein Einsatzfahrzeug kommt mit Blaulicht und Einsatzhorn. Was tust du?', ['Sofort freie Bahn schaffen', 'Nur bei Grün Platz machen', 'Weiterfahren, du hast Vorfahrt'], 0, 'Blaues Blinklicht zusammen mit dem Einsatzhorn ordnet an: alle anderen schaffen sofort freie Bahn.', 'StVO § 38 Abs. 1'),
    Wa('v-stau-kreuzung', 'vorfahrt', 'Grün, aber hinter der Kreuzung stockt der Verkehr. Was tust du?', ['Vor der Kreuzung warten', 'Einfahren, du hast Grün', 'Hupen'], 0, 'Du darfst nicht einfahren, wenn du auf der Kreuzung warten müsstest.', 'StVO § 11 Abs. 1'),
    Wa('v-verzicht', 'vorfahrt', 'Wann darfst du darauf vertrauen, dass jemand auf seine Vorfahrt verzichtet?', ['Wenn ihr euch verständigt habt', 'Wenn er langsamer wird', 'Wenn er nicht blinkt'], 0, 'Wer Vorrang hat, muss verzichten, wenn die Verkehrslage es erfordert.', 'StVO § 11 Abs. 3'),
    Wa('v-knick-blinken', 'vorfahrt', 'Du folgst einer abknickenden Vorfahrtstraße. Musst du blinken?', ['Ja', 'Nein, du bleibst auf der Vorfahrtstraße', 'Nur nach links'], 0, 'Wer dem Verlauf folgen will, muss das rechtzeitig und deutlich mit dem Blinker ankündigen.', 'StVO Anlage 3 Nr. 2.1'),
    Wa('v-301', 'vorfahrt', 'Wie weit gilt die Vorfahrt aus Zeichen 301?', ['Nur an der nächsten Kreuzung oder Einmündung', 'Bis Zeichen 307', 'Bis zum Ortsende'], 0, 'Zeichen 306 (Vorfahrtstraße) gilt dagegen bis zum nächsten Zeichen 205, 206 oder 307.', 'StVO Anlage 3 Nr. 1 und 2'),
    Wa('v-gruenpfeil', 'vorfahrt', 'Rot mit grünem Pfeilschild rechts daneben. Was gilt?', ['Erst anhalten, dann vorsichtig rechts abbiegen', 'Ohne Anhalten rechts abbiegen', 'Warten bis Grün'], 0, 'Abbiegen nur aus dem rechten Fahrstreifen, ohne Fußgänger oder den freigegebenen Verkehr zu behindern.', 'StVO § 37 Abs. 2 Nr. 1'),
    Wa('v-gelb', 'vorfahrt', 'Was ordnet Gelb an der Ampel an?', ['Vor der Kreuzung auf das nächste Zeichen warten', 'Schnell noch durchfahren', 'Nur für Linksabbieger halten'], 0, 'Die Farbfolge ist Grün – Gelb – Rot – Rot und Gelb – Grün.', 'StVO § 37 Abs. 2'),
    Wa('v-polizei-arm', 'vorfahrt', 'Ein Polizist hebt einen Arm. Was bedeutet das für dich vor der Kreuzung?', ['Auf das nächste Zeichen warten', 'Losfahren', 'Nur rechts abbiegen'], 0, 'Wer schon in der Kreuzung ist, muss sie räumen.', 'StVO § 36 Abs. 2 Nr. 2'),

    Z('s-warndreieck', 'sicher', 'Panne bei schnellem Verkehr: In etwa welcher Entfernung stellst du das Warndreieck auf?', 100, 'm', 'Vorher Warnblinklicht einschalten. Auf der Autobahn empfiehlt sich mehr Abstand (ADAC: mindestens 150 m), innerorts reichen etwa 50 m.', 'StVO § 15'),
    Z('s-nebelschluss', 'sicher', 'Unter welcher Sichtweite (Nebel) darfst du die Nebelschlussleuchte einschalten?', 50, 'm', 'Nur bei Nebel – und dann höchstens 50 km/h.', 'StVO § 17 Abs. 3'),
    Z('s-gefahr-abstand-min', 'sicher', 'Außerorts stehen Gefahrzeichen meist wie weit vor der Gefahrstelle? (Untergrenze)', 150, 'm', 'Üblich sind 150 bis 250 m. Ist es deutlich weniger, steht die Entfernung auf einem Zusatzzeichen.', 'StVO § 40 Abs. 2'),
    Z('s-bake3', 'sicher', 'Wie weit vor dem Bahnübergang steht die dreistreifige Bake?', 240, 'm', 'Zweistreifig: etwa 160 m, einstreifig: etwa 80 m.', 'StVO Anlage 1 Nr. 21 bis 23'),
    Z('s-bake1', 'sicher', 'Wie weit vor dem Bahnübergang steht die einstreifige Bake?', 80, 'm', 'Dreistreifig: etwa 240 m, zweistreifig: etwa 160 m.', 'StVO Anlage 1 Nr. 23'),
    Z('s-wasser', 'sicher', 'Ab wie vielen Litern wassergefährdender Ladung gilt Zeichen 269?', 20, 'l', 'Mit mehr als 20 l darfst du die Straße nicht benutzen.', 'StVO Anlage 2 Nr. 43'),
    Z('s-profil', 'sicher', 'Gesetzliche Mindestprofiltiefe bei Autoreifen?', 1.6, 'mm', 'Gemessen im Hauptprofil, also den breiten Rillen in der Mitte der Lauffläche.', 'StVZO § 36 Abs. 2'),
    Z('s-hoehe', 'sicher', 'Wie hoch dürfen Fahrzeug und Ladung auf Autobahnen und Kraftfahrstraßen höchstens sein?', 4, 'm', 'Die Breite ist auf 2,55 m begrenzt.', 'StVO § 18 Abs. 1'),
    Wa('s-rettungsgasse', 'sicher', 'Wo bildest du bei Stau auf einer dreispurigen Autobahn die Rettungsgasse?', ['Zwischen dem linken und dem mittleren Fahrstreifen', 'Zwischen dem mittleren und dem rechten Fahrstreifen', 'Auf dem Seitenstreifen'], 0, 'Immer zwischen dem ganz linken und dem rechts daneben liegenden Fahrstreifen – schon bei Schrittgeschwindigkeit.', 'StVO § 11 Abs. 2'),
    Wa('s-handy', 'sicher', 'Wann darfst du das Handy beim Fahren benutzen?', ['Nur ohne es aufzunehmen oder zu halten – per Sprache oder mit kurzem Blick', 'An der roten Ampel in der Hand', 'Bei Start-Stopp-Automatik im Stand'], 0, 'In der Hand nur bei stehendem Fahrzeug mit vollständig ausgeschaltetem Motor. Das automatische Abschalten durch Start-Stopp zählt nicht.', 'StVO § 23 Abs. 1a und 1b'),
    Wa('s-tunnel', 'sicher', 'Welches Licht ist im Tunnel (Zeichen 327) vorgeschrieben?', ['Abblendlicht', 'Standlicht', 'Tagfahrlicht reicht'], 0, 'Außerdem darfst du im Tunnel nicht wenden.', 'StVO Anlage 3 Nr. 14'),
    Wa('s-standlicht', 'sicher', 'Darfst du nur mit Standlicht fahren?', ['Nein, nie', 'Ja, innerorts', 'Ja, bei guter Straßenbeleuchtung'], 0, 'Auf durchgehend gut beleuchteten Straßen ist auch Fernlicht verboten.', 'StVO § 17 Abs. 2'),
    Wa('s-abschleppen', 'sicher', 'Du schleppst ein Auto ab, das auf der Autobahn liegen geblieben ist. Was gilt?', ['An der nächsten Ausfahrt die Autobahn verlassen', 'Bis zur Werkstatt auf der Autobahn bleiben', 'Auf dem Seitenstreifen abschleppen'], 0, 'Beide Fahrzeuge schalten das Warnblinklicht ein. Von außerhalb darf nicht auf die Autobahn eingefahren werden.', 'StVO § 15a'),
    Wa('s-autobahn-halten', 'sicher', 'Darfst du auf dem Seitenstreifen der Autobahn halten, um zu telefonieren?', ['Nein', 'Ja, kurz', 'Ja, mit Warnblinklicht'], 0, 'Halten ist auf der Autobahn verboten, auch auf dem Seitenstreifen. Bleibst du wegen einer Panne liegen, gilt § 15: Warnblinklicht an, Warndreieck aufstellen.', 'StVO § 18 Abs. 8'),
    Wa('s-unfall', 'sicher', 'Unfall mit geringem Schaden. Was tust du nach dem Anhalten und Sichern?', ['Unverzüglich beiseitefahren', 'Alles stehen lassen bis zur Polizei', 'Weiterfahren und später melden'], 0, 'Unfallspuren nicht beseitigen, bevor die nötigen Feststellungen getroffen sind.', 'StVO § 34 Abs. 1 und 3'),

    Z('f-kind-alter', 'person', 'Bis zu welchem Alter brauchen Kinder unter 150 cm im Auto einen Kindersitz?', 12, 'Jahre', 'Bis zum vollendeten 12. Lebensjahr, wenn sie kleiner als 150 cm sind.', 'StVO § 21 Abs. 1a'),
    Z('f-kind-groesse', 'person', 'Ab welcher Körpergröße braucht ein Kind keinen Kindersitz mehr?', 150, 'cm', 'Unabhängig davon endet die Pflicht mit dem 12. Geburtstag.', 'StVO § 21 Abs. 1a'),
    Z('f-promille', 'person', 'Ab welchem Promillewert ist das Fahren eine Ordnungswidrigkeit (ohne Ausfallerscheinungen)?', 0.5, '‰', 'In der Probezeit und unter 21 Jahren gilt 0,0 ‰. Mit Ausfallerscheinungen kann schon weniger strafbar sein.', 'StVG § 24a, § 24c'),
    Z('f-thc', 'person', 'THC-Grenzwert im Blutserum (Nanogramm pro Milliliter)?', 3.5, 'ng/ml', 'In der Probezeit und unter 21 Jahren ist Cannabis am Steuer ganz verboten.', 'StVG § 24a, § 24c'),
    Z('f-probezeit', 'person', 'Wie lange dauert die Probezeit beim ersten Führerschein?', 2, 'Jahre', 'Wird ein Aufbauseminar angeordnet, verlängert sie sich um zwei Jahre.', 'StVG § 2a'),
    Z('f-punkte', 'person', 'Ab wie vielen Punkten in Flensburg wird die Fahrerlaubnis entzogen?', 8, 'Punkte', 'Das Fahreignungs-Bewertungssystem kennt 8 Punkte als Grenze.', 'StVG § 4 Abs. 5'),
    Z('f-b-masse', 'person', 'Bis zu welcher zulässigen Gesamtmasse darfst du mit Klasse B fahren?', 3500, 'kg', 'Für höchstens acht Mitfahrer außer dem Fahrer.', 'FeV § 6 Abs. 1'),
    Z('f-b-anhaenger', 'person', 'Bis zu welcher zulässigen Gesamtmasse darf ein Anhänger bei Klasse B immer sein?', 750, 'kg', 'Schwerere Anhänger sind erlaubt, wenn das Gespann zusammen höchstens 3.500 kg zulässige Gesamtmasse hat.', 'FeV § 6 Abs. 1'),
    Z('f-b-personen', 'person', 'Wie viele Personen außer dem Fahrer darf ein Fahrzeug der Klasse B höchstens befördern können?', 8, 'Personen', 'Das Fahrzeug muss für nicht mehr als acht Personen außer dem Fahrer gebaut sein.', 'FeV § 6 Abs. 1'),
    Wa('f-gurt', 'person', 'Wie viele Personen darfst du im Auto mitnehmen?', ['So viele, wie Sitze mit Gurten da sind', 'So viele, wie reinpassen', 'Höchstens vier'], 0, 'Die Mitnahme auf der Ladefläche ist verboten.', 'StVO § 21 Abs. 1 und 2')
  ];

  /* ---------- Vorfahrt: Regeln zum Nachlesen ---------- */
  const VORFAHRT_REGELN = [
    { titel: 'Rechts vor links', text: 'An Kreuzungen und Einmündungen ohne Schilder oder Ampel hat Vorfahrt, wer von rechts kommt. Das gilt nicht für Fahrzeuge aus Feld- oder Waldwegen.', quelle: 'StVO § 8 Abs. 1' },
    { titel: 'Vorfahrtstraße und Wartepflicht', text: 'Zeichen 306 und 301 geben Vorfahrt, 205 und 206 nehmen sie. Bei 206 hältst du immer an – an der Haltlinie oder dort, wo du die Straße überblickst. Wer warten muss, zeigt das durch mäßige Geschwindigkeit und darf sich bei schlechter Sicht vorsichtig hineintasten.', quelle: 'StVO § 8 Abs. 2, Anlage 2 und 3' },
    { titel: 'Abbiegen und Gegenverkehr', text: 'Wer abbiegt, lässt entgegenkommende Fahrzeuge durchfahren. Linksabbieger lassen auch entgegenkommende Rechtsabbieger vor. Zwei Linksabbieger aus entgegengesetzten Richtungen biegen voreinander ab. Radfahrer, E-Scooter und Bahnen in gleicher Richtung haben beim Abbiegen Vorrang, auf Fußgänger nimmst du besondere Rücksicht.', quelle: 'StVO § 9 Abs. 3 und 4' },
    { titel: 'Abknickende Vorfahrt', text: 'Das Zusatzzeichen zeigt den Verlauf der Vorfahrtstraße. Wer ihm folgt, blinkt. Die Fahrzeuge auf der Vorfahrtstraße behandeln sich wie Gegenverkehr: Wer den Verlauf nach links verlässt, lässt entgegenkommende Fahrzeuge auf der Vorfahrtstraße durch. Die Wartepflichtigen lassen alle auf der Vorfahrtstraße vor – untereinander gilt rechts vor links.', quelle: 'StVO Anlage 3 Nr. 2.1, § 8, § 9' },
    { titel: 'Kreisverkehr', text: 'Steht Zeichen 215 mit Zeichen 205, hat der Verkehr im Kreis Vorfahrt. Beim Einfahren wird nicht geblinkt, beim Ausfahren rechts. Die Mittelinsel darfst du nicht überfahren, im Kreis nicht halten.', quelle: 'StVO § 8 Abs. 1a, Anlage 2 Nr. 8' },
    { titel: 'Einfahren aus Grundstücken', text: 'Wer aus einem Grundstück, einer Fußgängerzone, einem verkehrsberuhigten Bereich oder über einen abgesenkten Bordstein einfährt, muss eine Gefährdung anderer ausschließen – er lässt also alle durch.', quelle: 'StVO § 10' },
    { titel: 'Engstellen', text: 'Wer links an einem Hindernis vorbeifährt, lässt den Gegenverkehr durch – außer Zeichen 208 oder 308 regeln es anders.', quelle: 'StVO § 6' },
    { titel: 'Radweg und Abbiegen', text: 'Wer rechts abbiegt, kreuzt den Radweg neben der Fahrbahn. Radfahrer und E-Scooter, die geradeaus weiterfahren, haben Vorrang – auch wenn sie von hinten kommen. Mit Fahrzeugen über 3,5 t gilt innerorts beim Rechtsabbiegen Schrittgeschwindigkeit, wenn mit Radverkehr oder querenden Fußgängern zu rechnen ist.', quelle: 'StVO § 9 Abs. 3 und 6' },
    { titel: 'Bahn und Einsatzfahrzeuge', text: 'Am Andreaskreuz hat die Bahn Vorrang. Bei Blaulicht mit Einsatzhorn schaffen alle sofort freie Bahn. Stockt der Verkehr, fährst du trotz Vorfahrt oder Grün nicht in die Kreuzung ein.', quelle: 'StVO § 19, § 38, § 11' }
  ];
  const RANGFOLGE = [
    { titel: 'Polizei', text: 'Zeichen und Weisungen von Polizeibeamten gehen allem vor.', quelle: '§ 36' },
    { titel: 'Ampel', text: 'Lichtzeichen gehen Vorfahrtschildern und Vorrangregeln vor.', quelle: '§ 37' },
    { titel: 'Verkehrszeichen', text: 'Schilder gehen den allgemeinen Regeln vor.', quelle: '§ 39' },
    { titel: 'Grundregeln', text: 'Ohne all das: rechts vor links und die Regeln zum Abbiegen.', quelle: '§ 8, § 9' }
  ];

  global.Inhalte = { GRUPPEN, SCHILDER, THEMEN, FAKTEN, VORFAHRT_REGELN, RANGFOLGE };
})(window);
